name: Build Windows Executable

on: [ push ]  # Trigger the workflow on push events

jobs:
  build:
    runs-on: windows-latest  # Specifies that the job should run on the latest Windows runner

    steps:
      - uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install


      - name: Build Executable
        run: poetry run pyinstaller amachecker.spec

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: dist/*.exe
